apiVersion: apps/v1
kind: Deployment
metadata:
  name: baggage-producer
  namespace: baggage-poc
  labels:
    app: baggage-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baggage-producer
  template:
    metadata:
      labels:
        app: baggage-producer
    spec:
      containers:
        - name: producer
          image: baggage-producer:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: baggage-producer-config
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
